### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by WhiskyModz** [Ioopen/Android-Mod-Menu-Inject-Fixed#1]
Whenever I press inject the injector crashes

**Comment by Ioopen** [comment]
It works perfectly fine for me, so you're probably doing something incorrectly, such as trying it on an arm64 phone or vmos without re-inserting the injection code, or simply trying it on an emulator (Not Supported)

**Comment by WhiskyModz** [comment]
I tried on my rooted phone but it didn't work 
worked in vmos 
This work is being weird

**Comment by Ioopen** [comment]
Unfortunately, 64 bit is not supported (confirmed by nep himself) Perhaps try running the 32-bit version of the game? given that 64-bit devices can run 32-bit software without issue

**Comment by WhiskyModz** [comment]
I will try on 32 bit games
